FROM influxdb:latest

WORKDIR /

ENV DOCKER_INFLUXDB_INIT_MODE setup
ENV DOCKER_INFLUXDB_INIT_USERNAME admin 
ENV DOCKER_INFLUXDB_INIT_PASSWORD password 
ENV DOCKER_INFLUXDB_INIT_ORG web_tools 
ENV DOCKER_INFLUXDB_INIT_BUCKET web_tracking
ENV DOCKER_INFLUXDB_INIT_ADMIN_TOKEN password
ENV DOCKER_INFLUXDB_INIT_RETENTION 1w 
